version: '3.1'

services:
  postgres:
    image: postgres:15.1
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: reserves_app_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password123
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 5432:5432

    redis:
      image: redis:7.0.8
      ports: 
        -'6379:6379'